---
- name: test-playbook | Test sftp-server role
  hosts: test
#  sudo: yes
  roles:
    - ansible-sftp_jail
  vars_files:
    - 'defaults/main.yml'
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'