---
- name: variable output
  debug: msg="System {{ username }}"
- name: jail_sftp | Create sftp user group
  group: name=sftponly
         state=present

- name: jail_sftp | Alter sftp subsystem entry
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Subsystem sftp"
              line="Subsystem sftp internal-sftp"
              state=present
  notify: jail_sftp | Restart sshd

- name: jail_sftp | Test for Match Block
  shell: if [[ $(sed -n '/Match Group sftponly/,/ForceCommand internal-sftp/ { p }' /etc/ssh/sshd_config) ]]; then echo 'Match User Block Found'; else echo 'Not Found'; fi
  register: match_block_test
  changed_when: True == False

- name: jail_sftp | Get sshd_config content
  shell: sed -n '/Match Group sftponly/,/ForceCommand internal-sftp/! { p }' /etc/ssh/sshd_config
  register: sshd_config
  changed_when: True == False

# Create/recreate ssh_config.
- name: jail_sftp | Apply sshd_config template
  template: src=sshd_config.j2
            dest=/etc/ssh/sshd_config
            owner=root
  when: match_block_test.stdout.find("Not Found") != -1
  notify: jail_sftp | Restart sshd

# Create each SFTP user with home directory on the correct patition, and add to SFTP group.
- name: SFTP-Server | Create sftp users
  user: name={{ username }}
        groups=sftponly
        home="{{ homedir }}/{{ username }}"
        state=present

# A working chrooted SFTP setup requires root:sftgroup ownership of a user's home directory.
- name: jail_sftp | Correct ownership and permission of home directories
  file: path="{{ homedir }}/{{ username }}"
        owner=root
        group=sftponly
        mode="0750"
- debug: msg="System {{ pass }}"
# Update user passwords, if they were specified.
- name: jail_sftp | Update user passwords
  user: name={{ username }}
        password={{ pass }}

- name: jail_sftp | Get Site Name
  shell: echo "{{ mountroot }}" | grep -Eo '[^/]+/?$'
  register: sitename
- debug: msg="System {{ sitename.stdout }}"
- name: jail_sftp | Create Mount Folder
  file: path="{{ homedir }}/{{ username }}/{{ sitename.stdout }}"
        owner={{ username }}
        mode="0755"
        state=directory

- name: jail_sftp | Bind Mount
  mount: name="{{ homedir }}/{{ username }}/{{ sitename.stdout }}" src="{{ mountroot }}" fstype=none opts=rw,bind state=mounted